# Generated by Django 5.1.6 on 2025-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='phone_image/')),
            ],
            options={
                'verbose_name': 'SmartPhone',
                'ordering': ['-created_at'],
            },
        ),
    ]
